# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tele < Formula
  desc "TUI Telegram client"
  homepage "https://github.com/sorokin-vladimir/tele"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.2.0/tele_darwin_amd64.tar.gz"
      sha256 "69b0198e9cf4ac06ea1f0fc461ae9d927f40399cc12c49e59943f3d952d92a44"

      define_method(:install) do
        bin.install "tele"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.2.0/tele_darwin_arm64.tar.gz"
      sha256 "2d900389e2e081275c9f825baba6d83cda98cc9192fd16d638230bfce2d835b4"

      define_method(:install) do
        bin.install "tele"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.2.0/tele_linux_amd64.tar.gz"
      sha256 "85269fef7f2b6f0e358ba1224a4e849347d5e4d1801fb0fd7de5fdf0f487c250"
      define_method(:install) do
        bin.install "tele"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.2.0/tele_linux_arm64.tar.gz"
      sha256 "30db03484928d033f01bdedec37f3b51f40724c201e33204cb74d16314a18263"
      define_method(:install) do
        bin.install "tele"
      end
    end
  end

  test do
    system "#{bin}/tele", "--version"
  end
end
