# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tele < Formula
  desc "TUI Telegram client"
  homepage "https://github.com/sorokin-vladimir/tele"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.1.0/tele_darwin_amd64.tar.gz"
      sha256 "707261be3bcc8d6f4a7dc20adb06c08989baabf55b34dfdab4c3a47b814671e5"

      define_method(:install) do
        bin.install "tele"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.1.0/tele_darwin_arm64.tar.gz"
      sha256 "6099945cc1ac34cfca341e1bc6659a1233c12eab42249954d84fe5ff6c922f3f"

      define_method(:install) do
        bin.install "tele"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.1.0/tele_linux_amd64.tar.gz"
      sha256 "ae50762034335d56fbb91be5954ce5164dbc812fc2d7225681fba6429775723b"
      define_method(:install) do
        bin.install "tele"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorokin-vladimir/tele/releases/download/v1.1.0/tele_linux_arm64.tar.gz"
      sha256 "8ca529c020054ff5a278992e0d3d93afec85425e24b2d6103f5e35256b747cd0"
      define_method(:install) do
        bin.install "tele"
      end
    end
  end

  test do
    system "#{bin}/tele", "--version"
  end
end
